"""add info response message

Revision ID: f759be3cc038
Revises: 9b2d7f4e1c3a
Create Date: 2026-06-10 16:12:57.232660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f759be3cc038'
down_revision: Union[str, Sequence[str], None] = '9b2d7f4e1c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requests', sa.Column('info_response_message', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'purchase_requests', ['id'])
    op.create_unique_constraint(None, 'rate_limits', ['id'])
    op.create_unique_constraint(None, 'tiers', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tiers', type_='unique')
    op.drop_constraint(None, 'rate_limits', type_='unique')
    op.drop_constraint(None, 'purchase_requests', type_='unique')
    op.drop_column('purchase_requests', 'info_response_message')
    # ### end Alembic commands ###
